export const ARTICLES_ACTIONS_TYPES = {
  READ_ARTICLES_START: 'READ_ARTICLES_START',
  READ_ARTICLES_SUCCESS: 'READ_ARTICLES_SUCCESS',
  READ_ARTICLES_FAIL: 'READ_ARTICLES_FAIL',
  UPDATE_ARTICLES_START: 'UPDATE_ARTICLES_START',
  UPDATE_ARTICLES_SUCCESS: 'UPDATE_ARTICLES_SUCCESS',
  UPDATE_ARTICLES_FAIL: 'UPDATE_ARTICLES_FAIL',
  CREATE_ARTICLES_START: 'CREATE_ARTICLES_START',
  CREATE_ARTICLES_SUCCESS: 'CREATE_ARTICLES_SUCCESS',
  CREATE_ARTICLES_FAIL: 'CREATE_ARTICLES_FAIL',
  DELETE_ARTICLES_START: 'DELETE_ARTICLES_START',
  DELETE_ARTICLES_SUCCESS: 'DELETE_ARTICLES_SUCCESS',
  DELETE_ARTICLES_FAIL: 'DELETE_ARTICLES_FAIL',
}

export const TAGS_ACTIONS_TYPES = {
  READ_TAGS_START: 'READ_TAGS_START',
  READ_TAGS_SUCCESS: 'READ_TAGS_SUCCESS',
  READ_TAGS_FAIL: 'READ_TAGS_FAIL',
}
