import { SerializedError } from '@reduxjs/toolkit'
import { FetchBaseQueryError } from '@reduxjs/toolkit/dist/query/react'

import { ApiResponseError } from 'shared/types'

type UseMutationStateOptions = {
  // A method to determine the contents of `UseMutationResult`
  selectFromResult?: (result: unknown) => unknown
  // A string used to enable shared results across hook instances which have the same key
  fixedCacheKey?: string
}

type UseMutationTrigger<T> = (arg: unknown) => Promise<
  { data: T } | { error: SerializedError | FetchBaseQueryError }
> & {
  requestId: string // A string generated by RTK Query
  abort: () => void // A method to cancel the mutation promise
  unwrap: () => Promise<T> // A method to unwrap the mutation call and provide the raw response/error
  reset: () => void // A method to manually unsubscribe from the mutation call and reset the result to the uninitialized state
}

type UseMutationResult<T> = {
  // Base query state

  // Arguments passed to the latest mutation call. Not available if using the `fixedCacheKey` option
  originalArgs?: unknown
  // Returned result if present
  data?: T
  // Error result if present
  error?: SerializedError | FetchBaseQueryError
  // The name of the given endpoint for the mutation
  endpointName?: string
  // Timestamp for when the mutation was completed
  fulfilledTimeStamp?: number

  // Derived request status booleans

  // Mutation has not been fired yet
  isUninitialized: boolean
  // Mutation has been fired and is awaiting a response
  isLoading: boolean
  // Mutation has data from a successful call
  isSuccess: boolean
  // Mutation is currently in an "error" state
  isError: boolean
  // Timestamp for when the latest mutation was initiated
  startedTimeStamp?: number

  // A method to manually unsubscribe from the mutation call and reset the result to the uninitialized state
  reset: () => void
}

type UseMutationResultCustom<T> = Omit<UseMutationResult<T>, 'error'> & {
  error?: ApiResponseError
}

export type UseMutation<T> = (
  options?: UseMutationStateOptions
) => [UseMutationTrigger<T>, UseMutationResult<T>]

export const withUseMutation =
  <T>(useMutationFn: UseMutation<T>) =>
  (options?: UseMutationStateOptions) => {
    const [trigger, mutationResult] = useMutationFn(options)

    return [
      trigger,
      {
        ...mutationResult,
        error: mutationResult.error as unknown as ApiResponseError | undefined,
      },
    ] as unknown as [UseMutationTrigger<T>, UseMutationResultCustom<T>]
  }
