import { SerializedError } from '@reduxjs/toolkit'
import {
  FetchBaseQueryError,
  SkipToken,
} from '@reduxjs/toolkit/dist/query/react'

import { ApiResponseError } from 'shared/types'

type UseQueryOptions = {
  pollingInterval?: number
  skipPollingIfUnfocused?: boolean
  refetchOnReconnect?: boolean
  refetchOnFocus?: boolean
  skip?: boolean
  refetchOnMountOrArgChange?: boolean | number
  selectFromResult?: (result: unknown) => unknown
}

type UseQueryResult<T> = {
  // Base query state

  // Arguments passed to the query
  originalArgs?: unknown
  // The latest returned result regardless of hook arg, if present
  data?: T
  // The latest returned result for the current hook arg, if present
  currentData?: T
  // Error result if present
  error?: SerializedError | FetchBaseQueryError
  // A string generated by RTK Query
  requestId?: string
  // The name of the given endpoint for the query
  endpointName?: string
  // Timestamp for when the query was initiated
  startedTimeStamp?: number
  // Timestamp for when the query was completed
  fulfilledTimeStamp?: number

  // Derived request status booleans

  // Query has not started yet.
  isUninitialized: boolean
  // Query is currently loading for the first time. No data yet.
  isLoading: boolean
  // Query is currently fetching, but might have data from an earlier request.
  isFetching: boolean
  // Query has data from a successful load.
  isSuccess: boolean
  // Query is currently in an "error" state.
  isError: boolean

  // A function to force refetch the query - returns a Promise with additional methods
  refetch: () => void
}

export type UseQuery<T> = (
  arg: unknown | SkipToken,
  options?: UseQueryOptions
) => UseQueryResult<T>

export const withUseQuery =
  <T>(useQueryFn: UseQuery<T>) =>
  (arg?: unknown | SkipToken, options?: UseQueryOptions) => {
    const queryResult = useQueryFn(arg, options)

    return {
      ...queryResult,
      error: queryResult.error as unknown as ApiResponseError | undefined,
    }
  }
