import { SerializedError } from '@reduxjs/toolkit'
import {
  FetchBaseQueryError,
  SubscriptionOptions,
} from '@reduxjs/toolkit/dist/query/react'

import { ApiResponseError } from 'shared/types'

type UseLazyQueryOptions = {
  pollingInterval?: number
  skipPollingIfUnfocused?: boolean
  refetchOnReconnect?: boolean
  refetchOnFocus?: boolean
  selectFromResult?: (result: unknown) => unknown
}

type UseLazyQueryTrigger<T> = (
  arg: unknown,
  preferCacheValue?: boolean
) => Promise<unknown> & {
  // Whatever argument was provided to the query
  arg: unknown
  // A string generated by RTK Query
  requestId: string
  // The values used for the query subscription
  subscriptionOptions: SubscriptionOptions

  // A method to cancel the query promise
  abort: () => void
  // A method to unwrap the query call and provide the raw response/error
  unwrap: () => Promise<T>
  // A method used to manually unsubscribe from the query results
  unsubscribe: () => void
  // A method used to re-run the query. In most cases when using a lazy query, you will never use this and should prefer to call the trigger again.
  refetch: () => void
  // A method used to update the subscription options (eg. pollingInterval)
  updateSubscriptionOptions: (options: SubscriptionOptions) => void
}

type UseLazyQueryStateResult<T> = {
  // Base query state

  // Arguments passed to the query
  originalArgs?: unknown
  // The latest returned result regardless of hook arg, if present
  data?: T
  // The latest returned result for the current hook arg, if present
  currentData?: T
  // Error result if present
  error?: SerializedError | FetchBaseQueryError
  // A string generated by RTK Query
  requestId?: string
  // The name of the given endpoint for the query
  endpointName?: string
  // Timestamp for when the query was initiated
  startedTimeStamp?: number
  // Timestamp for when the query was completed
  fulfilledTimeStamp?: number

  // Derived request status booleans

  // Query has not started yet.
  isUninitialized: boolean
  // Query is currently loading for the first time. No data yet.
  isLoading: boolean
  // Query is currently fetching, but might have data from an earlier request.
  isFetching: boolean
  // Query has data from a successful load.
  isSuccess: boolean
  // Query is currently in an "error" state.
  isError: boolean
}

type UseLazyQueryStateResultCustom<T> = Omit<
  UseLazyQueryStateResult<T>,
  'error'
> & {
  error?: ApiResponseError
}

type UseLazyQueryLastPromiseInfo = {
  lastArg: unknown
}

export type UseLazyQuery<T> = (
  options?: UseLazyQueryOptions
) => [
  UseLazyQueryTrigger<T>,
  UseLazyQueryStateResult<T>,
  UseLazyQueryLastPromiseInfo,
]

export const withUseLazyQuery =
  <T>(useLazyQueryFn: UseLazyQuery<T>) =>
  (options?: UseLazyQueryOptions) => {
    const [trigger, lazyQueryResult, lastPromiseInfo] = useLazyQueryFn(options)

    return [
      trigger,
      {
        ...lazyQueryResult,
        error: lazyQueryResult.error as unknown as ApiResponseError | undefined,
      },
      lastPromiseInfo,
    ] as unknown as [
      UseLazyQueryTrigger<T>,
      UseLazyQueryStateResultCustom<T>,
      UseLazyQueryLastPromiseInfo,
    ]
  }
